// This code was generated by v0 by Vercel.
// @see https://v0.dev/t/7tQibiuZkZd

import React, { useEffect } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useChat } from "ai/react"; // Import ChatRequestOptions

export function Chatbot() {
  const { messages, input, handleInputChange, handleSubmit } = useChat({
    initialInput: "who is Ho Chi Minh"
  });


  return (
    <div className="h-96 w-full max-w-[700px]">
      <div className="flex flex-col h-full">
        <div className="flex-grow rounded-lg border p-4">
          {messages.map((m, index) => (
            <p className="whitespace-pre-line" key={index}>
              {m.content}
            </p>
          ))}
        </div>
        <div className="flex items-center p-2">
          <form className="flex-1" onSubmit={(e) => handleSubmit(e, {})}>
            {/* Pass an empty object for chatRequestOptions */}
            <Input
              placeholder="Type your message here..."
              value={input}
              onChange={handleInputChange}
            />
          </form>
          <Button className="ml-2" type="submit">
            Send
          </Button>
        </div>
      </div>
    </div>
  );
}
